---
sudo: false
language: ruby
cache: bundler
script: 'bundle exec rake validate lint spec'
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
notifications:
  email:
    - al@example42.com
